runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.app

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  application_readable: true

- url: /
  static_files: static/index.html
  upload: static/index.html
  application_readable: true

- url: /task/.*
  script: task.app
  login: admin